# SMV VerseCh++ests
# Author: Saimonovski
# Version: 2.0

#Do not change this
config-version: 4
#do not change this also
server-id: ""
#print additional information to console, turn on if bugs shown up then send logs to author of the plugin
debug-enabled: false

#Configuration of block using to create chests

blockCreator:
  material: BEDROCK
  name: "<gold> <bold>CreatorBlock"
  lore:
    - "<white> Place in to create a chest"
    - "<white> If you want to remove a chest destroy it while sneaking"
#Configuration a chest
chestConfiguration:
  material: CHEST
  title: "<purple> <bold> VerseChests" #Title showed in the gui
  minItems: 10
  maxItems: 25
  chestSize: 27
#How long (in seconds) player must be wait before open the same chest twice
chestCooldown: 3600

#configuration of rarity items (chancee to drop etc.)
# If you want to add your rarity just copy one of below sections and replace values
rarity:
  rare:
    chanceToDrop: 90 #In procent chance to drop item from this rarity setup
    maxItems: 10 #How many max items should be displayed in the chest
    minItems: 2 #How many min items should be displayed in the chest
  epic:
    chanceToDrop: 100 #In procent chance to drop item from this rarity setup
    maxItems: 10 #How many max items should be displayed in the chest
    minItems: 2 #How many min items should be displayed in the chest
  mythic:
    chanceToDrop: 100 #In procent chance to drop item from this rarity setup
    maxItems: 10 #How many max items should be displayed in the chest
    minItems: 2 #How many min items should be displayed in the chest
  legendary:
    chanceToDrop: 100 #In procent chance to drop item from this rarity setup
    maxItems: 10 #How many max items should be displayed in the chest
    minItems: 2 #How many min items should be displayed in the chest
